version: "2"         # required to adjust maintainability checks
checks:              # set same as in .pylintrc
  argument-count:
    config:
      threshold: 5
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 300
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 25
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 6
  similar-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.

plugins:
  bandit:
    enabled: true
  pep8:
    enabled: true
  radon: 
    enabled: true
    config: 
      threshold: "C"
  sonar-python:
    enabled: true
    checks:
      python:S117:
        enabled: false
      python:S125:
        enabled: false
      python:S1542:
        enabled: false


exclude_patterns:
  - "TestPyLeihe/"
